module.exports.authService = require('./auth.service')
module.exports.nodemailerService = require('./nodemailer.service')
module.exports.tokenService = require('./token.service')
module.exports.userService = require('./user.service')
module.exports.socialService = require('./social.service')
module.exports.postService = require('./post.service')
module.exports.commentService = require('./comment.service')
module.exports.likeService = require('./like.service')
